--------------------------------------------------------
--  File created - Friday-June-30-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TAS_REQUESTS
--------------------------------------------------------

  CREATE TABLE "WEBAPPS"."TAS_REQUESTS" 
   (	"REQUEST_ID" NUMBER, 
	"REQUEST_STUDENT_PIDM" NUMBER, 
	"REQUEST_COURSE" VARCHAR2(200 BYTE), 
	"REQUEST_DELIVERY_TYPE" VARCHAR2(250 BYTE), 
	"REQUEST_RETURN_TYPE" VARCHAR2(250 BYTE), 
	"REQUEST_DATE_SUBMITTED" DATE, 
	"REQUEST_PROFESSOR_PIDM" NUMBER, 
	"REQUEST_COURSE_CRN" VARCHAR2(20 BYTE), 
	"REQUEST_PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"REQUEST_COURSE_TIME" VARCHAR2(100 BYTE), 
	"REQUEST_PROFESSOR_EMAIL" VARCHAR2(200 BYTE), 
	"REQUEST_PROFESSOR_CAMPUS_ADDR" VARCHAR2(500 BYTE), 
	"REQUEST_PROFESSOR_APPROVED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"REQUEST_APPROVED_DATE" DATE, 
	"REQUEST_APPROVED_BY_PIDM" NUMBER, 
	"REQUEST_PROF_APPROVED_DATE" DATE, 
	"REQUEST_TAS_APPROVED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"REQUEST_REMINDER_DAYS" NUMBER, 
	"REQUEST_PROFESSOR_REACHED_BY" VARCHAR2(200 BYTE), 
	"REQUEST_ARCHIVED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"REQUEST_ARCHIVED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES" ;
--------------------------------------------------------
--  DDL for Index TAS_REQUESTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBAPPS"."TAS_REQUESTS_PK" ON "WEBAPPS"."TAS_REQUESTS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES" ;
--------------------------------------------------------
--  Constraints for Table TAS_REQUESTS
--------------------------------------------------------

  ALTER TABLE "WEBAPPS"."TAS_REQUESTS" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_REQUESTS" MODIFY ("REQUEST_STUDENT_PIDM" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_REQUESTS" MODIFY ("REQUEST_COURSE" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_REQUESTS" MODIFY ("REQUEST_DATE_SUBMITTED" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_REQUESTS" ADD CONSTRAINT "TAS_REQUESTS_PK" PRIMARY KEY ("REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES"  ENABLE;
  ALTER TABLE "WEBAPPS"."TAS_REQUESTS" MODIFY ("REQUEST_ARCHIVED" NOT NULL ENABLE);
