--------------------------------------------------------
--  File created - Friday-June-30-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TAS_REQUEST_NOTES
--------------------------------------------------------

  CREATE TABLE "WEBAPPS"."TAS_REQUEST_NOTES" 
   (	"NOTE_ID" NUMBER, 
	"NOTE_VALUE" CLOB, 
	"NOTE_REQUEST_ID" NUMBER, 
	"NOTE_ADDED_BY_PIDM" NUMBER, 
	"NOTE_ADDED_DATE" DATE, 
	"NOTE_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES" 
 LOB ("NOTE_VALUE") STORE AS SECUREFILE (
  TABLESPACE "LOCALTABLES" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index TAS_REQUEST_NOTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBAPPS"."TAS_REQUEST_NOTES_PK" ON "WEBAPPS"."TAS_REQUEST_NOTES" ("NOTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES" ;
--------------------------------------------------------
--  Constraints for Table TAS_REQUEST_NOTES
--------------------------------------------------------

  ALTER TABLE "WEBAPPS"."TAS_REQUEST_NOTES" ADD CONSTRAINT "TAS_REQUEST_NOTES_PK" PRIMARY KEY ("NOTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES"  ENABLE;
  ALTER TABLE "WEBAPPS"."TAS_REQUEST_NOTES" MODIFY ("NOTE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_REQUEST_NOTES" MODIFY ("NOTE_ADDED_DATE" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_REQUEST_NOTES" MODIFY ("NOTE_ADDED_BY_PIDM" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_REQUEST_NOTES" MODIFY ("NOTE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_REQUEST_NOTES" MODIFY ("NOTE_ID" NOT NULL ENABLE);
