--------------------------------------------------------
--  File created - Friday-June-30-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TAS_TEST_TIMES
--------------------------------------------------------

  CREATE TABLE "WEBAPPS"."TAS_TEST_TIMES" 
   (	"TEST_TIME_ID" NUMBER, 
	"TEST_TIME_REQUEST_ID" NUMBER, 
	"TEST_TIME_TYPE" VARCHAR2(20 BYTE), 
	"TEST_TIME_DATE" DATE, 
	"TEST_TIME_TITLE" VARCHAR2(200 BYTE), 
	"TEST_TIME_CANCELED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"TEST_TIME_CANCELED_BY_PIDM" NUMBER, 
	"TEST_TIME_CANCELED_DATE" DATE, 
	"TEST_TIME_NO_SHOW" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES" ;
--------------------------------------------------------
--  DDL for Index TAS_QUIZZES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBAPPS"."TAS_QUIZZES_PK" ON "WEBAPPS"."TAS_TEST_TIMES" ("TEST_TIME_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES" ;
--------------------------------------------------------
--  Constraints for Table TAS_TEST_TIMES
--------------------------------------------------------

  ALTER TABLE "WEBAPPS"."TAS_TEST_TIMES" MODIFY ("TEST_TIME_ID" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_TEST_TIMES" ADD CONSTRAINT "TAS_QUIZZES_PK" PRIMARY KEY ("TEST_TIME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES"  ENABLE;
  ALTER TABLE "WEBAPPS"."TAS_TEST_TIMES" MODIFY ("TEST_TIME_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_TEST_TIMES" MODIFY ("TEST_TIME_NO_SHOW" NOT NULL ENABLE);
