--------------------------------------------------------
--  File created - Friday-June-30-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TAS_ADMINISTRATORS
--------------------------------------------------------

  CREATE TABLE "WEBAPPS"."TAS_ADMINISTRATORS" 
   (	"ADMINISTRATOR_ID" NUMBER, 
	"ADMINISTRATOR_PIDM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES" ;
--------------------------------------------------------
--  DDL for Index TAS_ADMINISTRATORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBAPPS"."TAS_ADMINISTRATORS_PK" ON "WEBAPPS"."TAS_ADMINISTRATORS" ("ADMINISTRATOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES" ;
--------------------------------------------------------
--  Constraints for Table TAS_ADMINISTRATORS
--------------------------------------------------------

  ALTER TABLE "WEBAPPS"."TAS_ADMINISTRATORS" ADD CONSTRAINT "TAS_ADMINISTRATORS_PK" PRIMARY KEY ("ADMINISTRATOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES"  ENABLE;
  ALTER TABLE "WEBAPPS"."TAS_ADMINISTRATORS" MODIFY ("ADMINISTRATOR_PIDM" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_ADMINISTRATORS" MODIFY ("ADMINISTRATOR_ID" NOT NULL ENABLE);
