--------------------------------------------------------
--  File created - Friday-June-30-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TAS_ACCOMODATIONS
--------------------------------------------------------

  CREATE TABLE "WEBAPPS"."TAS_ACCOMODATIONS" 
   (	"ACCOMODATION_ID" NUMBER, 
	"ACCOMODATION_VALUE" VARCHAR2(2000 BYTE), 
	"ACCOMODATION_TYPE" VARCHAR2(20 BYTE), 
	"ACCOMODATION_REQUEST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES" ;
--------------------------------------------------------
--  DDL for Index TAS_ACCOMODATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBAPPS"."TAS_ACCOMODATIONS_PK" ON "WEBAPPS"."TAS_ACCOMODATIONS" ("ACCOMODATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES" ;
--------------------------------------------------------
--  Constraints for Table TAS_ACCOMODATIONS
--------------------------------------------------------

  ALTER TABLE "WEBAPPS"."TAS_ACCOMODATIONS" MODIFY ("ACCOMODATION_ID" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_ACCOMODATIONS" MODIFY ("ACCOMODATION_VALUE" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_ACCOMODATIONS" MODIFY ("ACCOMODATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WEBAPPS"."TAS_ACCOMODATIONS" ADD CONSTRAINT "TAS_ACCOMODATIONS_PK" PRIMARY KEY ("ACCOMODATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALTABLES"  ENABLE;
